### ISSUE TITLE
**Release:** staticfile-buildpack 1.5.22

### ISSUE THREAD

**Issue by cf-buildpacks-eng** [cloudfoundry/staticfile-buildpack#208] opened 2021-05-30 22:04 UTC
**Dependency Changes:**

```diff
nginx:
- 1.20.0
+ 1.20.1

```

**New Commits on Develop**:

8ac725a Auto merge pull request 206
314eb88 Add nginx 1.20.1, remove nginx 1.20.0
270bd10 Re-bootstraps with github-config
01efc57 Bootstraps with github-config
a1890f4 Update libbuildpack
abbb0cd Update libbuildpack

Refer to [release instructions](https://docs.cloudfoundry.org/buildpacks/releasing_a_new_buildpack_version.html).

**Comment by arjun024** [comment] 2021-06-11 18:15
Duplicate of #210

**Closed by arjun024** 2021-06-11 18:15 UTC
Labels: unscheduled
