### ISSUE TITLE
Pushstate and Pass Proxy Test Fails

### ISSUE THREAD

**Issue by pg85816** [cloudfoundry/staticfile-buildpack#157] opened 2019-05-21 14:14 UTC
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
"api_version": "2.94.0"
cf version 6.38.0+7ddf0aadd.2018-08-07

What version of the buildpack you are using?
1.4.41

If you were attempting to accomplish a task, what was it you were attempting to do?
Running the system integration tests.

What did you expect to happen?
All the tests to pass.

What was the actual behavior?
The deploy_pushstate_proxy_pass_test fails.

Please confirm where necessary:
* [X] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

`-bash-4.2$ ./scripts/integration.sh 
go: finding github.com/onsi/ginkgo/ginkgo latest
Run Cached Buildpack
cutlass.Cached true
Running Suite: Integration Suite
================================
Random Seed: 1558447135
Will run 1 of 1 specs

Pushing app pushstate_and_proxy_pass-cvxebmxdrlwsnqcuyata to org CATE / space development as admin...
Getting app info...
Creating app with these attributes...
+ name:         pushstate_and_proxy_pass-cvxebmxdrlwsnqcuyata
  path:         /home/pg85816/repos/staticfile-buildpack/fixtures/pushstate_and_proxy_pass
  buildpacks:
+   staticfile_buildpack
+ disk quota:   128M
+ memory:       128M
+ stack:        cflinuxfs2
  routes:
+   pushstateandproxypass-cvxebmxdrlwsnqcuyata.cfapps-dev3.citipaas.namdev.nsrootdev.net

Creating app pushstate_and_proxy_pass-cvxebmxdrlwsnqcuyata...
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 1.67 KiB / 1.67 KiB [================================================================================================] 100.00% 1s

Waiting for API to complete processing files...

name:              pushstate_and_proxy_pass-cvxebmxdrlwsnqcuyata
requested state:   stopped
routes:            pushstateandproxypass-cvxebmxdrlwsnqcuyata.cfapps-dev3.citipaas.namdev.nsrootdev.net
last uploaded:     
stack:             
buildpacks:        

type:           web
instances:      0/1
memory usage:   128M

There are no running instances of this process.

Starting app pushstate_and_proxy_pass-cvxebmxdrlwsnqcuyata in org CATE / space development as admin...

Staging app and tracing logs...
   Downloaded staticfile_buildpack (16.4M)
   Cell 66b85fe1-84fb-4ac9-8190-be73e7cf2b0a creating container for instance 064f3038-8e45-49eb-b7d0-c08f9a4fa0fa
   Cell 66b85fe1-84fb-4ac9-8190-be73e7cf2b0a successfully created container for instance 064f3038-8e45-49eb-b7d0-c08f9a4fa0fa
   Downloading app package...
   Downloaded app package (1.7K)
   -----> Staticfile Buildpack version 1.4.41.20190521095856
          **WARNING** 
          â ï¸ï¸ï¸ ð¨ï¸ï¸ â ï¸ ð¨ï¸ï¸
          This application is being deployed on cflinuxfs2 which is being deprecated in April, 2019.
          Please migrate this application to cflinuxfs3.
          For more information about changing the stack, see https://docs.cloudfoundry.org/devguide/deploy-apps/stacks.html
          â ï¸ï¸ï¸ ð¨ï¸ï¸ â ï¸ ð¨ï¸ï¸
   -----> Installing nginx
          Using nginx version 1.15.10
   -----> Installing nginx 1.15.10
          Copy [/tmp/buildpacks/e06ffc67813bc1a35f113afa3b0d026f/dependencies/71f300d5796c16db948e6d266b90036c/nginx-1.15.10-linux-x64-cflinuxfs2-6247377a.tgz]
   -----> Enabling location include file includes/*.conf
   -----> Enabling pushstate
   -----> Root folder /tmp/app/public
   -----> Copying project files into public
   -----> Configuring nginx
   Exit status 0
   Uploading droplet, build artifacts cache...
   Uploading build artifacts cache...
   Uploading droplet...
   Uploaded build artifacts cache (231B)
   Uploaded droplet (2.8M)
   Uploading complete

Waiting for app to start...
Start unsuccessful

TIP: use 'cf logs pushstate_and_proxy_pass-cvxebmxdrlwsnqcuyata --recent' for more information
FAILED
Deleting app pushstate_and_proxy_pass-cvxebmxdrlwsnqcuyata in org CATE / space development as admin...
OK
â¢ Failure in Spec Setup (BeforeEach) [230.452 seconds]
deploy a pushstate and reverse proxy app
/home/pg85816/repos/staticfile-buildpack/src/staticfile/integration/deploy_pushstate_and_proxy_pass_test.go:12
   [BeforeEach]
  /home/pg85816/repos/staticfile-buildpack/src/staticfile/integration/deploy_pushstate_and_proxy_pass_test.go:28

  Expected success, but got an error:
      <*exec.ExitError | 0xc000170020>: {
          ProcessState: {
              pid: 52361,
              status: 256,
              rusage: {
                  Utime: {Sec: 213, Usec: 58969},
                  Stime: {Sec: 0, Usec: 265930},
                  Maxrss: 14860,
                  Ixrss: 0,
                  Idrss: 0,
                  Isrss: 0,
                  Minflt: 4147,
                  Majflt: 0,
                  Nswap: 0,
                  Inblock: 0,
                  Oublock: 16,
                  Msgsnd: 0,
                  Msgrcv: 0,
                  Nsignals: 0,
                  Nvcsw: 23496,
                  Nivcsw: 3476,
              },
          },
          Stderr: nil,
      }
      exit status 1

  /home/pg85816/repos/staticfile-buildpack/src/staticfile/integration/integration_suite_test.go:78
------------------------------
^[[?1;2c^[[?1;2c^[[?1;2c^[[?1;2c^[[?1;2c^[[?1;2c^[[?1;2c^[[?1;2c

Summarizing 1 Failure:

[Fail] deploy a pushstate and reverse proxy app [BeforeEach]  
/home/pg85816/repos/staticfile-buildpack/src/staticfile/integration/integration_suite_test.go:78

Ran 1 of 1 Specs in 239.761 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 0 Skipped
--- FAIL: TestIntegration (239.76s)
FAIL

Ginkgo ran 1 suite in 4m1.31535495s
Test Suite Failed
`

**Comment by Zanadar** [comment] 2019-06-03 15:00
@pg85816 Not sure about your environment and setup, but we cannot reproduce this failure. Closing for now.

**Closed** 2019-06-03 15:00 UTC
Labels: unscheduled
